version: '3.7'
services:

  docmanager:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    env_file:
      - .env
    environment:
      - FIREBASE_APPLICATION_CREDENTIALS=/app/.data/firebaseServiceAccountKey.json
      - GOOGLE_DEFAULT_APPLICATION_CREDENTIALS=/app/.data/defaultServiceAccountKey.json
    ports:
      - 3000:3000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
